[package]
name = "aptos-rust-sdk-types"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aptos-crypto = { workspace = true }
aptos-crypto-derive = { workspace = true }

anyhow = { workspace = true }
aptos-bcs = { workspace = true }
hex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { workspace = true }
libsecp256k1 = { workspace = true }
tiny-keccak = { workspace = true }
serde_bytes = { workspace = true }
nom = "7.1"
ethnum = "1.5.2"
uint = "0.10.0"
num.workspace = true
primitive-types = "0.13.1"
